services:
  backend:
    build:
      context: .
      dockerfile: backend/docker/local/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./backend/.env
    volumes:
      - .:/var/www/html