services:
  backend:
    container_name: golf_backend
    build:
      context: ./backend
      dockerfile: docker/local/Dockerfile
    ports:
      - "8080:80"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/var/www/html